In [ ]:
import pandas as pd

# Load dataset
mahasiswa = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/Data Mahasiswa/Data Pribadi Mahasiswa 2023.xlsx", dtype={"NISN": str})  # Berisi informasi pribadi
ipk = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/IPK/IPK 2023.xlsx")  # Berisi IPK per mahasiswa
khs = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/KHS/Cleaned_KHS_2023.xlsx")  # Berisi nilai per mata kuliah per semester

# Pastikan kolom NIM dalam format string agar tidak terjadi mismatch
mahasiswa["NIM"] = mahasiswa["NIM"].astype(str)
ipk["NIM"] = ipk["NIM"].astype(str)
khs["NIM"] = khs["NIM"].astype(str)

# Gabungkan Data Mahasiswa dan IPK (One-to-One Join)
df_merged = pd.merge(mahasiswa, ipk, on="NIM", how="left")

# Gabungkan dengan KHS (One-to-Many Join, karena satu mahasiswa punya banyak mata kuliah)
df_final = pd.merge(df_merged, khs, on="NIM", how="left")

# Simpan hasil merge
df_final.to_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/dataset_gabungan_2023.xlsx", index=False)

# Tampilkan beberapa baris pertama untuk verifikasi
df_final

,No._x,NIM,Nama_x,NIK,JK,Agama,Kelas Perkuliahan,Tempat Lahir,Tanggal Lahir,Alamat,...,Sistem Kuliah,IPK Lulus,IPK Total,Nama,Program Studi,Pembimbing Akademik,Semester,Nama Mata Kuliah,SKS,Nilai Akhir
0,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,Reguler,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,MATEMATIKA KOMPUTER,3,A
1,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,Reguler,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,DASAR DASAR PEMROGRAMAN,3,A
2,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,Reguler,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,PENGANTAR TEKNOLOGI INFORMASI,3,A
3,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,Reguler,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,SISTEM OPERASI,3,A
4,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,Reguler,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,PEMROGRAMAN WEB 1,3,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6993,294,110123321,MUHAMMAD DZAWIL ARHAM,3171061109950001,Pria,Islam,23SI10,jakarta,1995-09-11 00:00:00,jalan matraman jaya no 1a rt 03 rw 04 keluraha...,...,Reguler,2.83,1.94,MUHAMMAD DZAWIL ARHAM,Sistem Informasi,"FARALITA FAISAL, S.Si, M.T.I",3,KEWIRAUSAHAAN,2,D
6994,294,110123321,MUHAMMAD DZAWIL ARHAM,3171061109950001,Pria,Islam,23SI10,jakarta,1995-09-11 00:00:00,jalan matraman jaya no 1a rt 03 rw 04 keluraha...,...,Reguler,2.83,1.94,MUHAMMAD DZAWIL ARHAM,Sistem Informasi,"FARALITA FAISAL, S.Si, M.T.I",3,BAHASA INGGRIS 2,2,D
6995,294,110123321,MUHAMMAD DZAWIL ARHAM,3171061109950001,Pria,Islam,23SI10,jakarta,1995-09-11 00:00:00,jalan matraman jaya no 1a rt 03 rw 04 keluraha...,...,Reguler,2.83,1.94,MUHAMMAD DZAWIL ARHAM,Sistem Informasi,"FARALITA FAISAL, S.Si, M.T.I",3,PENGANTAR SISTEM INFORMASI,3,B-
6996,294,110123321,MUHAMMAD DZAWIL ARHAM,3171061109950001,Pria,Islam,23SI10,jakarta,1995-09-11 00:00:00,jalan matraman jaya no 1a rt 03 rw 04 keluraha...,...,Reguler,2.83,1.94,MUHAMMAD DZAWIL ARHAM,Sistem Informasi,"FARALITA FAISAL, S.Si, M.T.I",3,DASAR-DASAR DESAIN,3,E
6997,294,110123321,MUHAMMAD DZAWIL ARHAM,3171061109950001,Pria,Islam,23SI10,jakarta,1995-09-11 00:00:00,jalan matraman jaya no 1a rt 03 rw 04 keluraha...,...,Reguler,2.83,1.94,MUHAMMAD DZAWIL ARHAM,Sistem Informasi,"FARALITA FAISAL, S.Si, M.T.I",3,MULTIMEDIA INTERAKTIF,3,E

In [ ]:
import pandas as pd

# Load dataset
mahasiswa = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/Data Mahasiswa/Data Pribadi Mahasiswa 2023.xlsx")  # Berisi informasi pribadi
ipk = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/IPK/IPK 2023.xlsx")  # Berisi IPK per mahasiswa
khs = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/KHS/Cleaned_KHS_2023.xlsx")  # Berisi nilai per mata kuliah per semester

# Pastikan kolom NIM dalam format string agar tidak terjadi mismatch
mahasiswa["NIM"] = mahasiswa["NIM"].astype(str)
ipk["NIM"] = ipk["NIM"].astype(str)
khs["NIM"] = khs["NIM"].astype(str)

# Gabungkan Data Mahasiswa dan IPK (One-to-One Join)
df_merged = pd.merge(mahasiswa, ipk, on="NIM", how="left")

# Gabungkan dengan KHS (One-to-Many Join, karena satu mahasiswa punya banyak mata kuliah)
df_final = pd.merge(df_merged, khs, on="NIM", how="left")

# Tentukan batasan untuk risiko lulus tepat waktu
IPK_MIN = 2.75  # IPK minimum untuk mahasiswa aman
RISK_GRADES = ['D', 'E']  # Nilai yang dianggap sebagai risiko

# Fungsi untuk menghitung rata-rata nilai akhir mahasiswa
def hitung_nilai_rata_rata(nim, df_khs):
    # Hitung rata-rata nilai untuk setiap mahasiswa berdasarkan NIM
    nilai_mapping = {'A': 4, 'A-': 3.7, 'B+': 3.3, 'B': 3, 'B-': 2.7, 'C+': 2.3, 'C': 2, 'C-': 1.7, 'D': 1, 'E': 0}
    nilai_mahasiswa = df_khs[df_khs['NIM'] == nim]['Nilai Akhir'].map(nilai_mapping)
    return nilai_mahasiswa.mean()

# Fungsi untuk menentukan apakah mahasiswa berisiko
def risiko_lulus(row):
    # Cek IPK
    ipk_risiko = row['IPK Total'] < IPK_MIN

    # Cek nilai rata-rata (apakah ada nilai D atau E yang dianggap berisiko?)
    nilai_rata_rata = hitung_nilai_rata_rata(row['NIM'], khs)
    nilai_risiko = nilai_rata_rata < 2.75  # Jika nilai rata-rata kurang dari 2.75, berisiko

    # Jika salah satu kondisi risiko terpenuhi, mahasiswa dianggap berisiko
    if ipk_risiko or nilai_risiko:
        return 'Berpotensi Terlambat'
    return 'Aman'

# Terapkan fungsi risiko_lulus ke setiap baris dalam dataset
df_final['Risiko Lulus'] = df_final.apply(risiko_lulus, axis=1)

# Simpan hasil gabungan dan penambahan kriteria risiko
df_final.to_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/dataset_risiko_gabungan_2023.xlsx", index=False)

# Tampilkan beberapa baris pertama untuk verifikasi
df_final.head()

,No._x,NIM,Nama_x,NIK,JK,Agama,Kelas Perkuliahan,Tempat Lahir,Tanggal Lahir,Alamat,...,IPK Lulus,IPK Total,Nama,Program Studi,Pembimbing Akademik,Semester,Nama Mata Kuliah,SKS,Nilai Akhir,Risiko Lulus
0,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,MATEMATIKA KOMPUTER,3,A,Aman
1,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,DASAR DASAR PEMROGRAMAN,3,A,Aman
2,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,PENGANTAR TEKNOLOGI INFORMASI,3,A,Aman
3,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,SISTEM OPERASI,3,A,Aman
4,1,110123001,SATRIO DWI PUJIANTO,3276100808030002,Pria,Islam,23SI02,JAKARTA,8 Agustus 2003,"KP. JATIJAJAR RT/08, RW/08, KEL JATIJAJAR, KEC...",...,3.96,3.96,SATRIO DWI PUJIANTO,Sistem Informasi,"Jemiro Kasih, S.T., M.M.S.I.",1,PEMROGRAMAN WEB 1,3,A,Aman

In [ ]:
import pandas as pd

# Load dataset
mahasiswa = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/Data Mahasiswa/Data Pribadi Mahasiswa 2023.xlsx")
ipk = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/IPK/IPK 2023.xlsx")
khs = pd.read_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/KHS/Cleaned_KHS_2023.xlsx")

# Format NIM ke string
for df in [mahasiswa, ipk, khs]:
    df["NIM"] = df["NIM"].astype(str)

# Mapping nilai
nilai_mapping = {'A': 4, 'A-': 3.7, 'B+': 3.3, 'B': 3, 'B-': 2.7, 'C+': 2.3, 'C': 2, 'C-': 1.7, 'D': 1, 'E': 0}
khs["Skor"] = khs["Nilai Akhir"].map(nilai_mapping)

# Ambil nilai tertinggi untuk matkul yang sama
khs = khs.sort_values(by=["NIM", "Nama Mata Kuliah", "Skor"], ascending=[True, True, False])
khs = khs.drop_duplicates(subset=["NIM", "Nama Mata Kuliah"], keep="first")

# Gabungkan data
df_merged = pd.merge(mahasiswa, ipk, on="NIM", how="left")
df_final = pd.merge(df_merged, khs, on="NIM", how="left")

# Tetapkan batas
IPK_MIN = 2.75
RISK_GRADES = ['C-', 'D', 'E']
batas_sks = {1: 20, 2: 20, 3: 21, 4: 20, 5: 20}

# Hitung total SKS per mahasiswa per semester (tanpa matkul E)
sks_per_semester = khs[~khs["Nilai Akhir"].isin(['C-', 'D', 'E'])].groupby(["NIM", "Semester"])["SKS"].sum().reset_index()
sks_per_semester.rename(columns={"SKS": "Total SKS"}, inplace=True)

# Gabungkan ke data final
df_final = pd.merge(df_final, sks_per_semester, on=["NIM", "Semester"], how="left")

# Tambahkan status SKS
def status_sks(row):
    batas = batas_sks.get(row['Semester'], 0)
    if pd.isna(row['Total SKS']) or row['Total SKS'] == 0:
        return "Tidak Aktif"
    elif row['Total SKS'] < batas:
        return "SKS Kurang"
    else:
        return "Aktif"

df_final["Status SKS"] = df_final.apply(status_sks, axis=1)

# Hitung IPS per baris (satu kolom)
def hitung_ips_baris(row, df_khs):
    nim = row['NIM']
    semester = row['Semester']
    data = df_khs[(df_khs['NIM'] == nim) & (df_khs['Semester'] == semester)]
    if data.empty or data['SKS'].sum() == 0:
        return None
    return round((data['SKS'] * data['Skor']).sum() / data['SKS'].sum(), 2)

df_final["IPS"] = df_final.apply(lambda row: hitung_ips_baris(row, khs), axis=1)

# Dictionary peminatan minimal 1 matkul
peminatan_dict = {
    'E-Business': {
        'PENGANTAR BISNIS DAN MANAJEMEN',
        'PENGANTAR BISNIS DIGITAL',
        'SISTEM INFORMASI AKUNTANSI'
    },
    'Enterprise': {
        'JAMINAN KUALITAS SISTEM INFORMASI',
        'SISTEM INFORMASI SDM',
        'ENTERPRISE RESOURCE PLANNING'
    },
    'User Experience': {
        'DASAR-DASAR DESAIN',
        'PRESENTASI DAN KOMUNIKASI VISUAL',
        'MULTIMEDIA INTERAKTIF'
    }
}

# Fungsi deteksi peminatan (minimal 1 matkul dari list)
def deteksi_peminatan(nim, df_khs):

    mk_all = set(df_khs[df_khs['NIM'] == nim]['Nama Mata Kuliah'].str.upper())
    for label, matkul_set in peminatan_dict.items():
        if mk_all.intersection(matkul_set):
            return label
    return 'Belum Teridentifikasi'

df_final['Peminatan'] = df_final['NIM'].apply(lambda nim: deteksi_peminatan(nim, khs))

# Fungsi risiko lulus
def risiko_lulus(row):
    ipk_risiko = row['IPK Total'] < IPK_MIN
    nilai_risiko = row['Nilai Akhir'] in RISK_GRADES
    sks_risiko = row["Status SKS"] in ["SKS Kurang", "Tidak Aktif"]
    return "Berpotensi Terlambat" if ipk_risiko or nilai_risiko or sks_risiko else "Aman"

df_final['Risiko Lulus'] = df_final.apply(risiko_lulus, axis=1)

# Simpan hasil akhir
df_final.to_excel("/content/drive/MyDrive/AKADEMIK KULIAH/(99) TUGAS AKHIR/Data TA/EWS 2023.xlsx", index=False)

# Cek hasil
df_final[['NIM', 'Nama', 'Semester', 'IPS', 'Status SKS', 'Peminatan', 'Risiko Lulus']].drop_duplicates().head()

,NIM,Nama,Semester,IPS,Status SKS,Peminatan,Risiko Lulus
0,110123001,SATRIO DWI PUJIANTO,1,4.00,Aktif,Enterprise,Aman
1,110123001,SATRIO DWI PUJIANTO,2,3.93,Aktif,Enterprise,Aman
2,110123001,SATRIO DWI PUJIANTO,3,3.96,Aktif,Enterprise,Aman
24,110123010,RISCA MARCELLA JHESICA,1,4.00,Aktif,Enterprise,Aman
25,110123010,RISCA MARCELLA JHESICA,2,3.96,Aktif,Enterprise,Aman